print("Hi \n\"I miss you\"")
x=float(input("1st number:  \n"))
y=float(input("2nd number:  \n"))
a=x*y
print(a)
print('I like "Monty Python"')
print("She said, 'I don't like going to the mall'")
print("She said, \'I don't like going to the mall\'")
print("Tell me anything...")
anything = input()
print("Hmm...", anything, "... Really?")