print("         *          "*2,end="\n\n")
print("       *   *        "*2,end="\n\n")
print("     *       *      "*2,end="\n\n")
print("   *           *    "*2,end="\n\n")
print(" * * *       * * *  "*2,end="\n\n")
print("     *       *      "*2,end="\n\n")
print("     *       *      "*2,end="\n\n")
print("     * * * * *      "*2,end="\n\n")
print()
print("I want you out of my head\nI want you out of my bedroom tonight\nThere's no way I can save you\nCuz I need to be saved too\nI'm no good at goodbyes")